### ISSUE TITLE
[request] ability to turn off world gen

### ISSUE THREAD

**Issue by majijn** [MelanX/morexfood#6]
would it be possible to have the option to choose whenever salt generates ? 
I have geolosys in charge of world ore gen for me, and I would like to use that for the salt generation.

would it be also possible to have an option to remove the replacement of vanilla village crops in farmlands?

**Comment by MelanX** [comment]
At the moment it isn't possible because I'm a noob at programming and modding. Maybe I can do it sometimes but not at the moment.

Vanilla crops will not be replaced. I just added my structure so it can spawn in villages, too. I just give my crops the chance to be generated in villages. So, no need to remove something :)

**Comment by majijn** [comment]
oh! I didnt know they werent replacing vanilla crops, either way part of the reason I wanted to remove them in my case is because villagers harvest them and make a mess

**Comment by MelanX** [comment]
yes, that's right.. I really don't know eh they do this.. I hope I'll find a solution. I don’t know how to create config files but I will try to create one.

**Comment by MelanX** [comment]
oh, I forgot to add villages to config, will add it soon
